version: 0.0
os: linux
files:
  - source: /
    destination: /opt/n_suzuki-sample/
hooks:
  BeforeInstall:
    - location: scripts/install_server
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root